engines:
  phpcodesniffer:
    enabled: true
ratings:
  paths:
  - bin/*
  - src/*
exclude_paths:
  - build/*
  - demo/*
  - doc/*
  - man/*
  - phpdoc/*
  - vendor/*
  - src/MarkdownExtendedDev/*
  - bin/mde-dev
  - tests/*
  - .sami.php
